# Generated by Django 2.1.2 on 2019-03-13 16:15

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('cellphone', models.CharField(blank=True, max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SPMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CIdOpcPadre', models.CharField(default='', max_length=36)),
                ('title', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=500)),
                ('link', models.CharField(max_length=500)),
                ('home', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Tblaplicacion',
            fields=[
                ('cidapp', models.CharField(db_column='CIdApp', default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('cnomapp', models.CharField(db_column='CNomApp', max_length=100, unique=True)),
                ('csnocultaropcnoautr', models.CharField(db_column='CSNOcultarOpcNoAutr', max_length=1)),
                ('csnaccesorapido', models.CharField(db_column='CSNAccesoRapido', max_length=1)),
                ('cceapp', models.CharField(db_column='CCeApp', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'tblaplicaciones',
                'db_table': 'tblaplicacion',
                'ordering': ('cidapp',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tblcliente',
            fields=[
                ('cidcliente', models.CharField(db_column='CIdCliente', default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('ccecliente', models.CharField(db_column='CCeCliente', default='A', max_length=1)),
                ('nflcreditocliente', models.FloatField(db_column='NFlCreditoCliente', default=0)),
            ],
            options={
                'verbose_name_plural': 'tblclientes',
                'db_table': 'tblcliente',
                'ordering': ('cidcliente',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tblclientetrans',
            fields=[
                ('cidclientetrans', models.CharField(db_column='CIdClienteTrans', default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('dfxtrans', models.DateTimeField(db_column='DFxTrans')),
                ('nflvalor', models.FloatField(db_column='NFlValor')),
                ('cdstrans', models.CharField(blank=True, db_column='CDsTrans', max_length=500, null=True)),
                ('cceclientetrans', models.CharField(db_column='CCeClienteTrans', default='A', max_length=1)),
                ('cidcliente', models.ForeignKey(db_column='CIdCliente', on_delete=django.db.models.deletion.DO_NOTHING, to='apirosamistica.Tblcliente')),
            ],
            options={
                'verbose_name_plural': 'tblclientetransacciones',
                'db_table': 'tblclientetrans',
                'ordering': ('cidclientetrans',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tblclientetransrecurso',
            fields=[
                ('cidclientetransrecurso', models.CharField(db_column='CIdClienteTransRecurso', default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('cceclientetransrecurso', models.CharField(db_column='CCeClienteTransRecurso', default='A', max_length=1)),
                ('cidclientetrans', models.ForeignKey(db_column='CIdClienteTrans', on_delete=django.db.models.deletion.DO_NOTHING, to='apirosamistica.Tblclientetrans')),
            ],
            options={
                'verbose_name_plural': 'tblclientetransrecursos',
                'db_table': 'tblclientetransrecurso',
                'ordering': ('cidclientetransrecurso',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tbleventoopcion',
            fields=[
                ('cideventoopc', models.CharField(db_column='CIdEventoOpc', default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('ccievento', models.CharField(db_column='CCiEvento', max_length=20)),
                ('cnomevento_en', models.CharField(db_column='CNomEvento_en', max_length=100)),
                ('cnomevento_es', models.CharField(db_column='CNomEvento_es', max_length=100)),
                ('cnomevento_ru', models.CharField(db_column='CNomEvento_ru', max_length=100)),
                ('cnomevento_zh', models.CharField(db_column='CNomEvento_zh', max_length=100)),
                ('ccisiglas', models.CharField(db_column='CCiSiglas', max_length=3)),
                ('nidpos', models.SmallIntegerField(db_column='NIdPos')),
                ('cceevento', models.CharField(db_column='CCeEvento', max_length=1)),
                ('cidapp', models.ForeignKey(db_column='CIdApp', on_delete=django.db.models.deletion.DO_NOTHING, to='apirosamistica.Tblaplicacion')),
            ],
            options={
                'verbose_name_plural': 'tbleventoopciones',
                'db_table': 'tbleventoopcion',
                'ordering': ('cideventoopc',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tblfinca',
            fields=[
                ('cidfinca', models.CharField(db_column='CIdFinca', default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('cnomfinca', models.CharField(db_column='CNomFinca', max_length=150, unique=True)),
                ('ctxubicacion', models.CharField(db_column='CTxUbicacion', max_length=500)),
                ('ccefinca', models.CharField(db_column='CCeFinca', default='A', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'tblfincas',
                'db_table': 'tblfinca',
                'ordering': ('cnomfinca',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tblflor',
            fields=[
                ('cidflor', models.CharField(db_column='CIdFlor', default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('cnomflor', models.CharField(db_column='CNomFlor', max_length=150, unique=True)),
                ('cceflor', models.CharField(db_column='CCeFlor', default='A', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'tblflores',
                'db_table': 'tblflor',
                'ordering': ('cnomflor',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tblflorfinca',
            fields=[
                ('cidflorfinca', models.CharField(db_column='CIdFlorFinca', default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('cceflorfinca', models.CharField(db_column='CCeFlorFinca', default='A', max_length=1)),
                ('cidfinca', models.ForeignKey(db_column='CIdFinca', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apirosamistica.Tblfinca')),
                ('cidflor', models.ForeignKey(db_column='CIdFlor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apirosamistica.Tblflor')),
            ],
            options={
                'verbose_name_plural': 'tblflorfincas',
                'db_table': 'tblflorfinca',
                'ordering': ('cidflorfinca',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tblflorpropiedad',
            fields=[
                ('cidflorpropiedad', models.CharField(db_column='CIdFlorPropiedad', default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('ctxvalorpropiedad', models.TextField(db_column='CTxValorPropiedad')),
                ('cidflor', models.ForeignKey(db_column='CIdFlor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apirosamistica.Tblflor')),
            ],
            options={
                'verbose_name_plural': 'tblflorfropiedades',
                'db_table': 'tblflorfropiedad',
                'ordering': ('cidflorpropiedad',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tblflorrecurso',
            fields=[
                ('cidflorrecurso', models.CharField(db_column='CIdFlorRecurso', default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('cceflorrecurso', models.CharField(db_column='CCeFlorRecurso', default='A', max_length=1)),
                ('cidflor', models.ForeignKey(db_column='CIdFlor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apirosamistica.Tblflor')),
            ],
            options={
                'verbose_name_plural': 'tblflorrecursos',
                'db_table': 'tblflorrecurso',
                'ordering': ('cidflorrecurso',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tblfuncion',
            fields=[
                ('cidfun', models.CharField(db_column='CIdFun', default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('ccifun', models.CharField(db_column='CCiFun', max_length=3)),
                ('cnomfun_en', models.CharField(db_column='CNomFun_en', max_length=100)),
                ('cnomfun_es', models.CharField(db_column='CNomFun_es', max_length=100)),
                ('cnomfun_ru', models.CharField(db_column='CNomFun_ru', max_length=100)),
                ('cnomfun_zh', models.CharField(db_column='CNomFun_zh', max_length=100)),
                ('nidpos', models.SmallIntegerField(db_column='NIdPos')),
                ('ccefun', models.CharField(db_column='CCeFun', max_length=1)),
                ('cidapp', models.ForeignKey(db_column='CIdApp', on_delete=django.db.models.deletion.DO_NOTHING, to='apirosamistica.Tblaplicacion')),
            ],
            options={
                'verbose_name_plural': 'tblfunciones',
                'db_table': 'tblfuncion',
                'ordering': ('cidfun',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tblmensaje',
            fields=[
                ('cidmensaje', models.CharField(db_column='CIdMensaje', max_length=36, primary_key=True, serialize=False)),
                ('cdstipoalerta', models.CharField(db_column='CDsTipoAlerta', default='success', max_length=20)),
                ('nnuduracion', models.SmallIntegerField(db_column='NNuDuracion', default=3)),
                ('cdstitle_en', models.CharField(db_column='CDsTitle_en', default='', max_length=100)),
                ('cdstitle_es', models.CharField(db_column='CDsTitle_es', default='', max_length=100)),
                ('cdstitle_ru', models.CharField(db_column='CDsTitle_ru', default='', max_length=100)),
                ('cdstitle_zh', models.CharField(db_column='CDsTitle_zh', default='', max_length=100)),
                ('cdsmsje_en', models.CharField(db_column='CDsMsje_en', default='', max_length=500)),
                ('cdsmsje_es', models.CharField(db_column='CDsMsje_es', default='', max_length=500)),
                ('cdsmsje_ru', models.CharField(db_column='CDsMsje_ru', default='', max_length=500)),
                ('cdsmsje_zh', models.CharField(db_column='CDsMsje_zh', default='', max_length=500)),
            ],
            options={
                'verbose_name_plural': 'tblmensajes',
                'db_table': 'tblmensaje',
                'ordering': ('cidmensaje',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tblmodulo',
            fields=[
                ('cidmod', models.CharField(db_column='CIdMod', default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('cnommod_en', models.CharField(db_column='CNomMod_en', max_length=100)),
                ('cnommod_es', models.CharField(db_column='CNomMod_es', max_length=100)),
                ('cnommod_ru', models.CharField(db_column='CNomMod_ru', max_length=100)),
                ('cnommod_zh', models.CharField(db_column='CNomMod_zh', max_length=100)),
                ('ccimod', models.CharField(db_column='CCiMod', max_length=3)),
                ('nidpos', models.SmallIntegerField(db_column='NIdPos')),
                ('ccemod', models.CharField(db_column='CCeMod', max_length=1)),
                ('cidapp', models.ForeignKey(db_column='CIdApp', on_delete=django.db.models.deletion.DO_NOTHING, to='apirosamistica.Tblaplicacion')),
            ],
            options={
                'verbose_name_plural': 'tblmodulos',
                'db_table': 'tblmodulo',
                'ordering': ('cidmod',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tblopcion',
            fields=[
                ('cidopc', models.CharField(db_column='CIdOpc', default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('ctxmenu_en', models.CharField(db_column='CTxMenu_en', max_length=100)),
                ('ctxmenu_es', models.CharField(db_column='CTxMenu_es', max_length=100)),
                ('ctxmenu_ru', models.CharField(db_column='CTxMenu_ru', max_length=100)),
                ('ctxmenu_zh', models.CharField(db_column='CTxMenu_zh', max_length=100)),
                ('nnunivel', models.SmallIntegerField(db_column='NNuNivel')),
                ('nnupos', models.SmallIntegerField(db_column='NNuPos')),
                ('cidopcpadre', models.CharField(db_column='CIdOpcPadre', max_length=36)),
                ('csnultimonivel', models.CharField(db_column='CSNUltimoNivel', max_length=1)),
                ('csnseparador', models.CharField(db_column='CSNSeparador', max_length=1)),
                ('cciclase', models.CharField(db_column='CCiClase', max_length=1)),
                ('ctxclase', models.CharField(db_column='CTxClase', max_length=500)),
                ('ctxargumento', models.CharField(blank=True, db_column='CTxArgumento', max_length=20, null=True)),
                ('ctxurlicono', models.CharField(db_column='CTxUrlIcono', max_length=500)),
                ('cidapp', models.ForeignKey(db_column='CIdApp', on_delete=django.db.models.deletion.DO_NOTHING, to='apirosamistica.Tblaplicacion')),
                ('cidfun', models.ForeignKey(db_column='CIdFun', on_delete=django.db.models.deletion.DO_NOTHING, to='apirosamistica.Tblfuncion')),
            ],
            options={
                'verbose_name_plural': 'tblopciones',
                'db_table': 'tblopcion',
                'ordering': ('cidopc',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tblparametro',
            fields=[
                ('cidparametro', models.CharField(db_column='CIdParametro', max_length=36, primary_key=True, serialize=False)),
                ('cnomparametro', models.CharField(db_column='CNomParametro', max_length=255, unique=True)),
                ('ctxtexto', models.CharField(blank=True, db_column='CTxTexto', max_length=200, null=True)),
                ('nnuvalor', models.FloatField(db_column='NNuValor')),
                ('cdsvaloresposibles', models.CharField(db_column='CDsValoresPosibles', max_length=500)),
            ],
            options={
                'verbose_name_plural': 'tblparametros',
                'db_table': 'tblparametro',
                'ordering': ('cidparametro',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tblpedidocabecera',
            fields=[
                ('cidpedido', models.CharField(db_column='CIdPedido', default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('cnumpedido', models.CharField(db_column='CNumPedido', max_length=10, unique=True)),
                ('dfxpedido', models.DateTimeField(db_column='DFxPedido')),
                ('cciestado', models.CharField(db_column='CCiEstado', max_length=1)),
                ('cnumprealert', models.CharField(db_column='CNumPreAlert', max_length=10)),
                ('dfxprealert', models.DateTimeField(blank=True, db_column='DFxPreAlert', null=True)),
                ('ccepedido', models.CharField(db_column='CCePedido', default='A', max_length=1)),
                ('cidcliente', models.ForeignKey(db_column='CIdCliente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apirosamistica.Tblcliente')),
            ],
            options={
                'verbose_name_plural': 'tblpedidocabeceras',
                'db_table': 'tblpedidocabecera',
                'ordering': ('cnumpedido',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tblpedidodetalle',
            fields=[
                ('cidpedidodet', models.CharField(db_column='CIdPedidoDet', default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('nnutam', models.SmallIntegerField(db_column='NNuTam')),
                ('ncanhb', models.SmallIntegerField(db_column='NCanHB')),
                ('ncanqb', models.SmallIntegerField(db_column='NCanQB')),
                ('ncantallos', models.IntegerField(db_column='NCanTallos')),
                ('nvrpreciounit', models.FloatField(db_column='NVrPrecioUnit')),
                ('cdssolicitud', models.CharField(db_column='CDsSolicitud', max_length=100)),
                ('cidfinca', models.ForeignKey(blank=True, db_column='CIdFinca', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apirosamistica.Tblfinca')),
                ('cidflor', models.ForeignKey(db_column='CIdFlor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apirosamistica.Tblflor')),
                ('cidpedido', models.ForeignKey(db_column='CIdPedido', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apirosamistica.Tblpedidocabecera')),
            ],
            options={
                'verbose_name_plural': 'tblpedidodetalles',
                'db_table': 'tblpedidodetalle',
                'ordering': ('cidpedidodet',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tblpedidoestadodetalle',
            fields=[
                ('cidpedidoestadodet', models.CharField(db_column='CIdPedidoEstadoDet', default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('cnompedidoestadodet', models.CharField(db_column='CNomPedidoEstadoDet', max_length=50, unique=True)),
                ('ccepedidoestadodet', models.CharField(db_column='CCePedidoEstadoDet', default='A', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'tblpedidoestadodetalles',
                'db_table': 'tblpedidoestadodetalle',
                'ordering': ('cnompedidoestadodet',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tblpermisoeventoopcion',
            fields=[
                ('cidpermevenopc', models.CharField(db_column='CIdPermEvenOpc', default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('ccepermevenopc', models.CharField(db_column='CCePermEvenOpc', max_length=1)),
                ('cideventoopc', models.ForeignKey(db_column='CIdEventoOpc', default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='permisoevento_evento', to='apirosamistica.Tbleventoopcion')),
            ],
            options={
                'verbose_name_plural': 'tblpermisoeventoopciones',
                'db_table': 'tblpermisoeventoopcion',
                'ordering': ('cidpermevenopc',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tblpermisoopcion',
            fields=[
                ('cidpermopc', models.CharField(db_column='CIdPermOpc', default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('ccepermopc', models.CharField(db_column='CCePermOpc', max_length=1)),
                ('cidopc', models.ForeignKey(db_column='CIdOpc', default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='permiso_opcion', to='apirosamistica.Tblopcion')),
            ],
            options={
                'verbose_name_plural': 'tblpermisoopciones',
                'db_table': 'tblpermisoopcion',
                'ordering': ('cidpermopc',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tblpersona',
            fields=[
                ('cidpersona', models.CharField(db_column='CIdPersona', default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('cnompersona', models.CharField(db_column='CNomPersona', max_length=150)),
                ('capepersona', models.CharField(db_column='CApePersona', max_length=150)),
                ('ccepersona', models.CharField(db_column='CCePersona', default='A', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'tblpersonas',
                'db_table': 'tblpersona',
                'ordering': ('capepersona', 'cnompersona'),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tblpersonapropiedad',
            fields=[
                ('cidpersonapropiedad', models.CharField(db_column='CIdPersonaPropiedad', default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('ctxvalorpropiedad', models.TextField(db_column='CTxValorPropiedad')),
                ('cidpersona', models.ForeignKey(db_column='CIdPersona', on_delete=django.db.models.deletion.DO_NOTHING, to='apirosamistica.Tblpersona')),
            ],
            options={
                'verbose_name_plural': 'tblpersonapropiedades',
                'db_table': 'tblpersonapropiedad',
                'ordering': ('cidpersonapropiedad',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tblpropiedad',
            fields=[
                ('cidpropiedad', models.CharField(db_column='CIdPropiedad', default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('cnompropiedad', models.CharField(db_column='CNomPropiedad', max_length=100, unique=True)),
                ('ctxetiqueta', models.CharField(db_column='CTxEtiqueta', max_length=50)),
                ('ccitipodato', models.CharField(db_column='CCiTipoDato', max_length=1)),
                ('nnulongitud', models.SmallIntegerField(db_column='NNuLongitud', default=0)),
                ('ccepropiedad', models.CharField(db_column='CCePropiedad', default='A', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'tblpropiedades',
                'db_table': 'tblpropiedad',
                'ordering': ('cnompropiedad',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tblrecurso',
            fields=[
                ('cidrecurso', models.CharField(db_column='CIdRecurso', default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('ccitiporecurso', models.CharField(db_column='CCiTipoRecurso', max_length=3)),
                ('cnomrecurso', models.CharField(db_column='CNomRecurso', max_length=255)),
                ('ctxrutarecurso', models.CharField(db_column='CTxRutaRecurso', max_length=500)),
                ('ccerecurso', models.CharField(db_column='CCeRecurso', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'tblrecursos',
                'db_table': 'tblrecurso',
                'ordering': ('cidrecurso',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tblrol',
            fields=[
                ('cidrol', models.CharField(db_column='CIdRol', default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('cnomrol', models.CharField(db_column='CNomRol', max_length=100, unique=True)),
                ('ccerol', models.CharField(db_column='CCeRol', default='A', max_length=1)),
                ('ctxurlicono', models.CharField(db_column='CTxUrlIcono', default='', max_length=500)),
            ],
            options={
                'verbose_name_plural': 'roles',
                'db_table': 'tblrol',
                'ordering': ('cnomrol',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tblrolusuario',
            fields=[
                ('cidrolusuario', models.CharField(db_column='CIdRolUsuario', default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('ccerolusuario', models.CharField(db_column='CCeRolUsuario', default='A', max_length=1)),
                ('cidrol', models.ForeignKey(db_column='cidrol', default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='rol', to='apirosamistica.Tblrol')),
            ],
            options={
                'verbose_name_plural': 'tblrolusuarios',
                'db_table': 'tblrolusuario',
                'ordering': ('cidrolusuario',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tbltipotrans',
            fields=[
                ('cidtipotrans', models.CharField(db_column='CIdTipoTrans', default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('cnomtipotrans', models.CharField(db_column='CNomTipoTrans', max_length=50, unique=True)),
                ('ccetipotrans', models.CharField(db_column='CCeTipoTrans', default='A', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'tbltipotransacciones',
                'db_table': 'tbltipotrans',
                'ordering': ('cnomtipotrans',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tblusuario',
            fields=[
                ('cidusuario', models.CharField(db_column='CIdUsuario', default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('cnomusuario', models.CharField(db_column='CNomUsuario', max_length=50, unique=True)),
                ('ctxclave', models.CharField(db_column='CTxClave', max_length=255)),
                ('ctxcorreo', models.CharField(db_column='CTxCorreo', max_length=150, unique=True)),
                ('cnucelular', models.CharField(db_column='CNuCelular', max_length=20, unique=True)),
                ('cceusuario', models.CharField(db_column='CCeUsuario', default='A', max_length=1)),
                ('cidpersona', models.ForeignKey(db_column='CIdPersona', on_delete=django.db.models.deletion.DO_NOTHING, to='apirosamistica.Tblpersona')),
            ],
            options={
                'verbose_name_plural': 'tblusuarios',
                'db_table': 'tblusuario',
                'ordering': ('cnomusuario',),
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='tblrolusuario',
            name='cidusuario',
            field=models.ForeignKey(db_column='CIdUsuario', default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='rol_usuario', to='apirosamistica.Tblusuario'),
        ),
        migrations.AddField(
            model_name='tblpersonapropiedad',
            name='cidpropiedad',
            field=models.ForeignKey(db_column='CIdPropiedad', on_delete=django.db.models.deletion.DO_NOTHING, to='apirosamistica.Tblpropiedad'),
        ),
        migrations.AddField(
            model_name='tblpermisoopcion',
            name='cidrol',
            field=models.ForeignKey(db_column='CIdRol', default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='permiso_rol', to='apirosamistica.Tblrol'),
        ),
        migrations.AddField(
            model_name='tblpermisoeventoopcion',
            name='cidpermopc',
            field=models.ForeignKey(db_column='CIdPermOpc', default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='permisoevento_opcion', to='apirosamistica.Tblpermisoopcion'),
        ),
        migrations.AddField(
            model_name='tblpedidodetalle',
            name='cidpedidoestadodet',
            field=models.ForeignKey(db_column='CIdPedidoEstadoDet', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apirosamistica.Tblpedidoestadodetalle'),
        ),
        migrations.AddField(
            model_name='tblflorrecurso',
            name='cidrecurso',
            field=models.ForeignKey(db_column='CIdRecurso', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apirosamistica.Tblrecurso'),
        ),
        migrations.AddField(
            model_name='tblflorpropiedad',
            name='cidpropiedad',
            field=models.ForeignKey(db_column='CIdPropiedad', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apirosamistica.Tblpropiedad'),
        ),
        migrations.AddField(
            model_name='tblclientetransrecurso',
            name='cidrecurso',
            field=models.ForeignKey(db_column='CIdRecurso', on_delete=django.db.models.deletion.DO_NOTHING, to='apirosamistica.Tblrecurso'),
        ),
        migrations.AddField(
            model_name='tblclientetrans',
            name='cidtipotrans',
            field=models.ForeignKey(db_column='CIdTipoTrans', on_delete=django.db.models.deletion.DO_NOTHING, to='apirosamistica.Tbltipotrans'),
        ),
        migrations.AddField(
            model_name='tblclientetrans',
            name='cidusuario',
            field=models.ForeignKey(db_column='CIdUsuario', default='', on_delete=django.db.models.deletion.DO_NOTHING, to='apirosamistica.Tblusuario'),
        ),
        migrations.AddField(
            model_name='tblcliente',
            name='cidrolusuario',
            field=models.ForeignKey(db_column='CIdRolUsuario', on_delete=django.db.models.deletion.DO_NOTHING, to='apirosamistica.Tblrolusuario'),
        ),
    ]
