# Generated by Django 2.1.2 on 2019-03-25 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apirosamistica', '0002_auto_20190325_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblflorrecurso',
            name='cidrecurso',
            field=models.ForeignKey(db_column='CIdRecurso', default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='flor_recursos', to='apirosamistica.Tblrecurso'),
        ),
    ]
